# Generated by Django 4.2 on 2023-04-26 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('submission_name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('hackathon_title', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField()),
            ],
        ),
    ]
